[features]
seeds = false

[programs.localnet]
chain_signatures = "SigLqW12jGkFFc6Sc6s2QtJTxVGGScr8VH5MViktgdy"
proxy_test_cpi = "76SSSaQQjQ35d8shjHUsUNFwfpnJamVAiCN5hWzuF84f"

[programs.devnet]
chain_signatures = "SigDuEPNeDjh3oJv7MUraPN7zaTFomS6ZWfpXwjUg4B"
proxy_test_cpi = "76SSSaQQjQ35d8shjHUsUNFwfpnJamVAiCN5hWzuF84f"

[programs.testnet]
chain_signatures = "SigTVbfRK9LsXWpSv9KgpabrQcFKr5hDdUwMhYsXyKg"
proxy_test_cpi = "76SSSaQQjQ35d8shjHUsUNFwfpnJamVAiCN5hWzuF84f"

[programs.mainnet]
chain_signatures = "SigMcRMjKfnC7RDG5q4yUMZM1s5KJ9oYTPP4NmJRDRw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 100000

[scripts]
test = "NODE_OPTIONS='--import tsx/esm' yarn run mocha --exit -t 1000000 tests/*.spec.ts"

[toolchain]
anchor_version = "0.31.1"